# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
  - 2.7
# Need to set this so that packages installed with apt-get are available
virtualenv:
  system_site_packages: true
env:
  - OMP_NUM_THREADS=4
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose sphinx imaging
  - pip install -q --use-mirrors coverage coveralls pep8
  # Test the docs build before installing because sphinx breaks on Cython modules
  - cd doc; sphinx-build -W -d _build/doctrees -b html . _build/html; cd ..
install:
  - python setup.py build_ext --inplace
script:
  - nosetests fatiando test -v --with-doctest --with-coverage --cover-package=fatiando
after_success:
  - coveralls
notifications:
  email: false
