# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
# and the seaborn package
language: python

sudo: false

env:
  global: # For pushing the built docs to the fatiando.github.io repo
    - secure: cXRXecOJ0LpQBPfl/CvrrvuDTQpN0zZ1mpGG4rs02yWRmRoykqzJpPNHBHZ1MWEHGwOP9QqXjuPTRPEHYBP4I9V/7uHgrd4rIg50gonyr0LdQFLL9QxsM6SMH/zHyma+hpWmg2k3ad6zBd0GFkaACtVlS/x2F8JG+W6TrU/oL+I=
  matrix:
    - PYTHON=2.7

before_install:
  # Get Miniconda from Continuum
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - cp ci-tools/matplotlibrc .

install:
  - conda create -n testenv --yes pip python=$PYTHON
  - conda update conda --yes
  - source activate testenv
  - conda install --yes --file requirements.txt
  - conda install --yes --file test/requirements-conda.txt
  - pip install -r test/requirements-pip.txt
  - pip install .
  - python setup.py build_ext --inplace

script:
  - make test
  - make coverage
  - make docs

after_success:
  - coveralls
  - bash ci-tools/update-website.sh

after_failure:
  - make pep8

notifications:
  email: false
